kind: Template
apiVersion: v1
metadata:
  name: che-quarkus-demo-backend
  labels:
    app: che-quarkus-demo
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: che-quarkus-demo-backend
    labels:
      app: che-quarkus-demo
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: che-quarkus-demo-backend
    template:
      metadata:
        labels:
          app: che-quarkus-demo-backend
      spec:
        containers:
        - env:
          -  name: REACT_APP_BACKEND_HOST
             value: thisisjustatest
          image: amisevsk/che-demo-backend
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /posts
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            failureThreshold: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /posts
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            failureThreshold: 5
            timeoutSeconds: 5
          name: che-quarkus-demo-backend
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 24Mi
        restartPolicy: Always
    triggers:
    - type: ConfigChange
